nombresObjetos = [
"Poción",
"Megapoción",
"Poción máxima",
"Poción antigua",
"Antídoto",
"Medicina herbal",
"Curibaya",
"Bebida energética",
"Ración",
"Filete poco hecho",
"Filete al punto",
"Carne quemada",
"Bebida fría",
"Bebida caliente",
"Nutrientes",
"Meganutrientes",
"Inmunizador",
"Cecina de Astera",
"Zumo de poder",
"Semilla de poder",
"Droga demoníaca",
"Megadroga demoníaca",
"Píldora de poder",
"Semilla armadura",
"Piel de armadura",
"Piel de armadura+",
"Píldora armadura",
"Polvo de vida",
"Fuente de vida",
"Polvo de hierbas",
"Polvo de demonio",
"Polvo de cáscara",
"Miel",
"Hierba",
"Hierba antídoto",
"Hierba de fuego",
"Helechoflor",
"Hierba de nieve",
"Hierba somnífera",
"Hiedra",
"Guindilla",
"Brote nocturno",
"Nuez de humo",
"Baya antidragón",
"Seta azul",
"Mandrágora",
"Nitroseta",
"Mancha del diablo",
"Paraliseta",
"Hongo",
"Seta excitante",
"Fresquiñón",
"Bicho amargo",
"Luminsecto",
"Bicho divino",
"Electrobicho",
"Insecto goloso",
"Cuerno de Kelbi",
"Extracto de poder",
"Extracto nutritivo",
"Vesícula lanzagritos",
"Catalizador",
"Bola tranquilizante",
"Cápsula flash",
"Cápsula chillona",
"Cápsula boñiga",
"Bola de humo",
"Bola de humo venenoso",
"Bola transportadora",
"Carne cruda",
"Carne envenenada",
"Carne tóxica",
"Carne somnífera",
"Pólvora",
"Barril pequeño",
"Bomba de barril",
"Bomba de rebote",
"Mega bomba de rebote",
"Barril grande",
"Bomba de barril grande",
"Megabomba de barril",
"Telaraña",
"Red",
"Herramientas para trampas",
"Trampa de escollo",
"Trampa eléctrica",
"Boñiga enrollada",
"Boñiga",
"Cebo de arrowana",
"Cebo de pez pólvora",
"Cebo de pez dorado",
"Bumerán",
"Prismáticos",
"Amuleto de poder",
"Garra de poder",
"Amuleto armadura",
"Garra armadura",
"Baya aguja",
"Nuez pegajosa",
"Nuez dragoniana",
"Rajabaya",
"Baya adherente",
"Baya bomba",
"Flamanuez",
"Ardenuez",
"Pólvora nivel 2",
"Pólvora nivel 3",
"Fuegos primaverales",
"Fuegos de la puesta de sol",
"Fuegos de la cosecha",
"Fuegos artificiales estrella",
"Fuegos de gratitud",
"Frasco vacío",
"Aleta de caballa cuchillo",
"Aleta de caballa cuchillo+",
"Escama de pez sushi",
"Escama de pez sushi real",
"Escama de pez pólvora",
"Escama de pez pólvora real",
"Escama de arrowana reventona",
"Escama arrowana reventona real",
"Escama de arrowana bomba",
"Escama de arrowana bomba real",
"Hierro",
"Machalita",
"Dragonita",
"Carbalita",
"Fucium",
"Eltalita",
"Flexidur",
"Cristal de tierra",
"Cristal coralino",
"Cristal de dracovena",
"Cristal de vena espiritual",
"Cristal reluciente",
"Novacristal",
"Cristal puro",
"Piedra de lava",
"Baticita",
"Gracio",
"Oceanita",
"Solitrabita",
"Sanguinita",
"Lazurita",
"Espectrita",
"Oscurita",
"Hueso recio",
"Hueso escogido",
"Hueso grueso",
"Hueso antiguo",
"Hueso fósil",
"Hueso de coral",
"Hueso deforme",
"Hueso brutal",
"Cráneo desconocido",
"Hueso congelado",
"Reliquia de dracohueso",
"Artefacto de dracohueso",
"Esfera armadura",
"Esfera armadura+",
"Esfera armadura avanz.",
"Esfera armadura dura",
"Esfera armadura pesada",
"Esfera armadura regia",
"Esfera armadura pura",
"Esquirla de dracolucia",
"Dracolucia",
"Dracolucia grande",
"Dracolucia rígida",
"Dracolucia pura",
"Gran mosca cornuda",
"Tela siniestra",
"Metal ancestral",
"Esquirla de dracovena",
"Carbón de dracovena",
"Pieza de carbón de dracovena",
"Carbón de dracovena gigante",
"Hueso monstruo pequeño",
"Hueso monstruo mediano",
"Hueso monstruo grande",
"Hueso de monstruo+",
"Hueso afilado",
"Hueso escudo",
"Hueso ultraduro",
"Hueso aplastante",
"Hueso sólido",
"Hueso de dragón anciano",
"Gran hueso de dragón anciano",
"Garra afilada",
"Garra perforante",
"Garra dura",
"Fluido de monstruo",
"Caldo de monstruo",
"Esencia de monstruo",
"Vesícula de veneno",
"Vesícula tóxica",
"Vesícula de veneno mortal",
"Vesícula paralizante",
"Vesícula neural",
"Vesícula concentrada",
"Vesícula somnífera",
"Vesícula de coma",
"Vesícula de letargo",
"Vesícula flamígera",
"Vesícula infernal",
"Vesícula explosiva",
"Vesícula acuosa",
"Vesícula torrencial",
"Vesícula lago",
"Vesícula de nieve",
"Vesícula congelante",
"Vesícula gélida",
"Vesícula eléctrica",
"Vesícula de rayo",
"Vesícula relámpago",
"Gema wyvern pájaro",
"Gema mística de wyvern",
"Gema de wyvern",
"Gran gema de wyvern",
"Sangre de dragón anciano",
"Sangre pura de dragón",
"Gran gema de dragón anciano",
"Piel de Musgorrino",
"Piel cálida",
"Piel de alta calidad",
"Piel valiosa",
"Cuerno de Anteka",
"Caparazón de Vespoid",
"Coraza de Vespoid",
"Ala de Vespoid",
"Ala interior de Vespoid",
"Ala cuchilla de Vespoid",
"Caparazón de Hornetaur",
"Coraza de Hornetaur",
"Ala de Hornetaur",
"Intraala de Hornetaur",
"Ala cuchilla de Hornetaur",
"Cabeza de Hornetaur",
"Piel de Gajau",
"Escama de Gajau",
"Piel gruesa de Gajau",
"Bigote de Gajau",
"Gran bigote de Gajau",
"Bigote de Gajau acerado",
"Piel de dracoalado",
"Piel de dracoalado+",
"Piel especial de dracoalado",
"Piel de Barnos+",
"Garra de Barnos",
"Garra dura de Barnos",
"Garra dura de Kertos",
"Caparazón de Kestodon",
"Coraza de Kestodon",
"Cascarón de Kestodon",
"Crin de Kestodon",
"Coraza de Gastodon",
"Cascarón de Gastodon",
"Cuerno de Gastodon",
"Escama de Jagras",
"Escama de Jagras+",
"Esquirla de Jagras",
"Piel de Jagras",
"Piel de Jagras+",
"Escama de Shamos",
"Escama de Shamos+",
"Esquirla de Shamos",
"Piel de Shamos",
"Piel de Shamos+",
"Escama de Girros",
"Escama de Girros+",
"Esquirla de Girros",
"Piel de Girros",
"Piel de Girros+",
"Colmillo de Girros",
"Pelaje de Wulg",
"Escama de Gran Jagras",
"Escama de Gran Jagras+",
"Esquirla de Gran Jagras",
"Piel de Gran Jagras",
"Piel de Gran Jagras+",
"Piel gruesa de Gran Jagras",
"Garra de Gran Jagras",
"Garra de Gran Jagras+",
"Garra dura de Gran Jagras",
"Melena de Gran Jagras",
"Melena de Gran Jagras+",
"Escama de Kulu-Ya-Ku",
"Escama de Kulu-Ya-Ku+",
"Esquirla de Kulu-Ya-Ku",
"Piel de Kulu-Ya-Ku",
"Piel de Kulu-Ya-Ku+",
"Piel gruesa de Kulu-Ya-Ku",
"Pluma de Kulu-Ya-Ku",
"Pluma de Kulu-Ya-Ku+",
"Gran pluma Kulu-Ya-Ku",
"Pico de Kulu-Ya-Ku",
"Pico de Kulu-Ya-Ku+",
"Gran pico Kulu-Ya-Ku",
"Escama de Pukei-Pukei",
"Escama de Pukei-Pukei+",
"Esquirla de Pukei-Pukei",
"Caparazón de Pukei-Pukei",
"Coraza de Pukei-Pukei",
"Córtex de Pukei-Pukei",
"Péndola de Pukei-Pukei",
"Ala de Pukei-Pukei",
"Aladura de Pukei-Pukei",
"Vesícula de Pukei-Pukei",
"Vesícula de Pukei-Pukei+",
"Vesícula grande de Pukei-Pukei",
"Cola de Pukei-Pukei",
"Látigo de Pukei-Pukei",
"Esquirla de Pukei-Pukei Coralino",
"Córtex de Pukei-Pukei Coralino",
"Aladura de Pukei-Pukei Coralino",
"Vesícula gr. Pukei-Pukei Coralino",
"Látigo de Pukei-Pukei Coralino",
"Caparazón de Barroth",
"Coraza de Barroth",
"Córtex de Barroth",
"Cresta de Barroth",
"Cresta de Barroth+",
"Espinazo de Barroth",
"Garra de Barroth",
"Garra de Barroth+",
"Garra dura de Barroth",
"Cuero cabelludo de Barroth",
"Corona de Barroth",
"Cola de Barroth",
"Látigo de Barroth",
"Barro fértil",
"Barro enriquecido",
"Escama de Jyuratodus",
"Escama de Jyuratodus+",
"Esquirla de Jyuratodus",
"Caparazón de Jyuratodus",
"Coraza de Jyuratodus",
"Córtex de Jyuratodus",
"Colmillo de Jyuratodus",
"Colmillo de Jyuratodus+",
"Colmillo duro de Jyuratodus",
"Aleta de Jyuratodus",
"Aleta de Jyuratodus+",
"Gran aleta de Jyuratodus",
"Esquirla de Beotodus",
"Córtex de Beotodus",
"Asta de Beotodus",
"Gran aleta de Beotodus",
"Escama de Tobi-Kadachi",
"Escama de Tobi-Kadachi+",
"Esquirla de Tobi-Kadachi",
"Piel de Tobi-Kadachi",
"Piel de Tobi-Kadachi+",
"Pelaje de Tobi-Kadachi",
"Membrana de Tobi-Kadachi",
"Membrana de Tobi-Kadachi+",
"Garra de Tobi-Kadachi",
"Garra de Tobi-Kadachi+",
"Garra dura de Tobi-Kadachi",
"Electrodo de Tobi-Kadachi",
"Electrodo de Tobi-Kadachi+",
"Cátodo de Tobi-Kadachi",
"Esquirla de Tobi-Kadachi Vípero",
"Pelaje de Tobi-Kadachi Vípero",
"Membrana Tobi-Kadachi Vípero+",
"Garra dura de Tobi-Kadachi Vípero",
"Espina Tobi-Kadachi Vípero",
"Córtex de Banbaro",
"Lomo de Banbaro",
"Gran cuerno de Banbaro",
"Látigo de Banbaro",
"Escama de Anjanath",
"Escama de Anjanath+",
"Esquirla de Anjanath",
"Piel de Anjanath",
"Piel de Anjanath+",
"Pelo de Anjanath",
"Colmillo de Anjanath",
"Colmillo de Anjanath+",
"Colmillo duro de Anjanath",
"Hueso nasal de Anjanath",
"Hueso nasal de Anjanath+",
"Hueso nasal pesado de Anjanath",
"Cola de Anjanath",
"Látigo de Anjanath",
"Placa de Anjanath",
"Gema de Anjanath",
"Manto de Anjanath",
"Esquirla de Anjanath Fulgúreo",
"Pelaje de Anjanath Fulgúreo",
"Colmillo duro de Anjanath Fulgúreo",
"Hueso nasal pesado Anja Fulgúreo",
"Látigo de Anjanath Fulgúreo",
"Manto de Anjanath Fulgúreo",
"Escama de Rathian",
"Escama de Rathian+",
"Esquirla de Rathian",
"Caparazón de Rathian",
"Coraza de Rathian",
"Córtex de Rathian",
"Membrana de Rathian",
"Tejido de Rathian",
"Púa de Rathian",
"Púa de Rathian+",
"Aguja de Rathian",
"Placa de Rathian",
"Rubí de Rathian",
"Manto de Rathian",
"Escama de Rathian Rosa+",
"Esquirla de Rathian Rosa",
"Coraza de Rathian Rosa",
"Córtex de Rathian Rosa",
"Esquirla de Rathian Dorada",
"Córtex de Rathian Dorada",
"Aguja de Rathian Dorada",
"Escama de Tzitzi-Ya-Ku",
"Escama de Tzitzi-Ya-Ku+",
"Esquirla de Tzitzi-Ya-Ku",
"Piel de Tzitzi-Ya-Ku",
"Piel de Tzitzi-Ya-Ku+",
"Piel gruesa de Tzitzi-Ya-Ku",
"Garra de Tzitzi-Ya-Ku",
"Garra de Tzitzi-Ya-Ku+",
"Garra dura de Tzitzi-Ya-Ku",
"Fotóforo de Tzitzi-Ya-Ku",
"Fotóforo de Tzitzi-Ya-Ku+",
"Fotomembrana de Tzitzi-Ya-Ku",
"Piel de Paolumu",
"Piel de Paolumu+",
"Pelaje de Paolumu",
"Escama de Paolumu",
"Escama de Paolumu+",
"Esquirla de Paolumu",
"Caparazón de Paolumu",
"Coraza de Paolumu+",
"Córtex de Paolumu",
"Membrana de Paolumu",
"Ala de Paolumu",
"Aladura de Paolumu",
"Pelaje de Paolumu Somnus",
"Esquirla de Paolumu Somnus",
"Aladura de Paolumu Somnus",
"Escama de Gran Girros",
"Escama de Gran Girros+",
"Esquirla de Gran Girros",
"Piel de Gran Girros",
"Piel de Gran Girros+",
"Piel gruesa de Gran Girros",
"Capucha de Gran Girros",
"Capucha de Gran Girros+",
"Capucha dura de Gran Girros",
"Colmillo de Gran Girros",
"Colmillo de Gran Girros+",
"Colmillo duro de Gran Girros",
"Cola de Gran Girros",
"Látigo de Gran Girros",
"Escama de Radobaan",
"Escama de Radobaan+",
"Esquirla de Radobaan",
"Caparazón de Radobaan",
"Coraza de Radobaan",
"Córtex de Radobaan",
"Aceite de Radobaan",
"Aceite de Radobaan+",
"Hueso de wyvern",
"Gran hueso de wyvern",
"Tuétano de Radobaan",
"Médula de Radobaan",
"Escama de Legiana",
"Escama de Legiana+",
"Esquirla de Legiana",
"Piel de Legiana",
"Piel de Legiana+",
"Piel gruesa de Legiana",
"Garra de Legiana",
"Garra de Legiana+",
"Garra dura de Legiana",
"Membrana de Legiana",
"Ala de Legiana",
"Aladura de Legiana",
"Membrana de cola de Legiana",
"Membrana de cola de Legiana+",
"Placa de Legiana",
"Gema de Legiana",
"Manto de Legiana",
"Piel escarchada",
"Garra de hielo de obsidiana",
"Ala inhóspita",
"Escama de Odogaron",
"Escama de Odogaron+",
"Esquirla de Odogaron",
"Tendón de Odogaron",
"Tendón de Odogaron+",
"Tendón duro de Odogaron",
"Garra de Odogaron",
"Garra de Odogaron+",
"Garra dura de Odogaron",
"Colmillo de Odogaron",
"Colmillo de Odogaron+",
"Colmillo duro de Odogaron",
"Cola de Odogaron",
"Látigo de Odogaron",
"Placa de Odogaron",
"Gema de Odogaron",
"Manto de Odogaron",
"Esquirla de Odogaron Ébano",
"Tendón duro de Odogaron Ébano",
"Garra dura de Odogaron Ébano",
"Colmillo duro de Odogaron Ébano",
"Látigo de Odogaron Ébano",
"Manto de Odogaron Ébano",
"Escama de Rathalos",
"Escama de Rathalos+",
"Esquirla de Rathalos",
"Caparazón de Rathalos",
"Coraza de Rathalos",
"Córtex de Rathalos",
"Membrana de Rathalos",
"Ala de Rathalos",
"Aladura de Rathalos",
"Cola de Rathalos",
"Látigo de Rathalos",
"Garra de Rath",
"Garra de Rath+",
"Tuétano de Rath",
"Médula de Rathalos",
"Placa de Rathalos",
"Rubí de Rathalos",
"Manto de Rathalos",
"Escama de Rathalos Celeste+",
"Esquirla de Rathalos Celeste",
"Coraza de Rathalos Celeste",
"Córtex de Rathalos Celeste",
"Cola de Rathalos Celeste",
"Látigo de Rathalos Celeste",
"Ala de Rathalos Celeste",
"Aladura de Rathalos Celeste",
"Esquirla de Rathalos Plateado",
"Córtex de Rathalos Plateado",
"Aladura de Rathalos Plateado",
"Látigo de Rathalos Plateado",
"Destello de Rath",
"Caparazón de Diablos",
"Coraza de Diablos",
"Córtex de Diablos",
"Cresta de Diablos",
"Cresta de Diablos+",
"Espinazo de Diablos",
"Colamen de Diablos",
"Colamen de Diablos+",
"Colmillo de Diablos",
"Cuerno retorcido",
"Cuerno majestuoso",
"Pitón sólido",
"Asta de Diablos",
"Médula de Diablos",
"Médula de Blos",
"Coraza de Diablos Negra",
"Córtex de Diablos Negra",
"Cresta de Diablos Negra+",
"Espinazo de Diablos Negra",
"Colmillo negro en espiral+",
"Pitón enroscado",
"Escama de Dodogama+",
"Esquirla de Dodogama",
"Piel de Dodogama+",
"Piel gruesa de Dodogama",
"Mandíbula de Dodogama",
"Mandíbula de Dodogama",
"Garra de Dodogama",
"Garra dura de Dodogama",
"Cola de Dodogama",
"Látigo de Dodogama",
"Escama de Lavasioth+",
"Esquirla de Lavasioth",
"Coraza de Lavasioth",
"Córtex de Lavasioth",
"Colmillo de Lavasioth+",
"Colmillo duro de Lavasioth",
"Aleta de Lavasioth+",
"Gran aleta de Lavasioth",
"Escama de Uragaan+",
"Esquirla de Uragaan",
"Coraza de Uragaan",
"Córtex de Uragaan",
"Mandíbula de Uragaan",
"Mandíbula de Uragaan+",
"Peto de Uragaan",
"Peto de Uragaan+",
"Tuétano de Uragaan",
"Rubí de Uragaan",
"Palio de Uragaan",
"Pepita de lava",
"Córtex de Barioth",
"Pelaje de Barioth",
"Garra dura de Barioth",
"Púa gigante de Barioth",
"Látigo de Barioth",
"Colmillo duro de ámbar",
"Piel de nieve plateada",
"Garra rompehielo",
"Colmillo de hielo plateado",
"Esquirla de Nargacuga",
"Pelaje negro de Nargacuga+",
"Látigo de Nargacuga",
"Colapúa de Nargacuga",
"Cuchilla de Nargacuga+",
"Colmillo duro de Nargacuga",
"Manto de Nargacuga",
"Esquirla de Tigrex",
"Córtex de Tigrex",
"Látigo de Tigrex",
"Garra dura de Tigrex",
"Colmillo duro de Tigrex",
"Manto de Tigrex",
"Esquirla de Tigrex Pardo",
"Córtex de Tigrex Pardo",
"Garra dura de Tigrex Pardo",
"Colmillo duro de Tigrex Pardo",
"Esquirla de Glavenus",
"Córtex de Glavenus",
"Colmillo duro de Glavenus",
"Caparazón infernal de Glavenus",
"Punta de cola de Glavenus",
"Bolsa magmática",
"Manto de Glavenus",
"Esquirla de Glavenus Acídico",
"Córtex de Glavenus Acídico",
"Colmillo duro de Glavenus Acídico",
"Caparazón púas Glavenus Acídico",
"Punta de cola Glavenus Acídico",
"Cristalácido refinado",
"Córtex de Brachydios",
"Ébano perfecto de Brachydios",
"Corona de Brachydios",
"Baba brillante",
"Mazo de Brachydios+",
"Látigo de Brachydios",
"Palio de Brachydios",
"Caparacébano indestructible",
"Ojiva Brach",
"Baba detonante",
"Desintegrador Brach",
"Reactor inmortal",
"Esquirla de Garuga",
"Córtex de Garuga",
"Aurícula de Garuga",
"Pico llamativo",
"Aladura de Garuga",
"Látigo de Garuga",
"Argentopiel de Garuga",
"Caparazón rayado",
"Córtex de Zinogre",
"Electropelo de Zinogre+",
"Cuerno duro de Zinogre",
"Garra dura de Zinogre",
"Látigo Zinogre",
"Electrificador letal Zinogre",
"Lumiarañas",
"Cielada Zinogre",
"Córtex de Zinogre Estigio",
"Crin de Zinogre Estigio",
"Asta de Zinogre Estigio",
"Garra dura de Zinogre Estigio",
"Látigo de Zinogre Estigio",
"Dracáscara de Zinogre Estigio",
"Bicho dracófago",
"Cielada de Zinogre Estigio",
"Escama de Bazelgeuse+",
"Esquirla de Bazelgeuse",
"Coraza de Bazelgeuse",
"Caparazón de plata brillante",
"Cola de Bazelgeuse",
"Flagelo de Bazelgeuse",
"Espoleta de Bazelgeuse",
"Fluido nitro destilado",
"Garra de Bazelgeuse",
"Garra dura de Bazelgeuse",
"Ala de Bazelgeuse",
"Alaplata abrasadora",
"Gema de Bazelgeuse",
"Manto de Bazelgeuse",
"Escama de Deviljho",
"Esquirla de Deviljho",
"Piel de Deviljho",
"Piel negra de Deviljho",
"Colmillo de Deviljho",
"Colmillo feroz",
"Garra de Deviljho",
"Destripadora de Deviljho",
"Cráneo de Deviljho",
"Cola de Deviljho",
"Flagelo de Deviljho",
"Saliva de Deviljho",
"Sangre negra",
"Gema de Deviljho",
"Cayado de Deviljho",
"Asta de Rajang",
"Colmillo duro de Rajang",
"Pelaje Rajang negro",
"Garra dura de Rajang",
"Cola de Rajang",
"Piel de Rajang+",
"Melena de Rajang",
"Cuerno dorado espectral",
"Corazón de Rajang",
"Piel de Kirin",
"Piel de Kirin+",
"Piel de Kirin especial",
"Cola de Kirin",
"Cola rayo de Kirin",
"Cola rayo de Kirin+",
"Crin de Kirin",
"Crin plateada de Kirin",
"Cuerno rayo de Kirin",
"Cuerno de Kirin celeste",
"Cuerno de Kirin Celeste+",
"Escama ígnea Zorah Magdaros",
"Coraza de Zorah Magdaros",
"Cresta de Zorah Magdaros",
"Pleura de Zorah Magdaros",
"Magma de Zorah Magdaros",
"Gema de Zorah Magdaros",
"Escama de dragón inmortal",
"Esquirla inmortal",
"Coraza de Nergigante",
"Córtex de Nergigante",
"Cola de Nergigante",
"Flagelo de Nergigante",
"Cuerno de Nergigante+",
"Gran cuerno aniquilador",
"Garra de Nergigante",
"Garra dura de Nergigante",
"Placa regeneración Nergigante",
"Placa de regeneración eterna",
"Gema de Nergigante",
"Esquirla de cristal",
"Córtex de Velkhana",
"Aladura de Velkhana",
"Cornacorona de Velkhana",
"Látigo de Velkhana",
"Garra dura de Velkhana",
"Cristal de Velkhana",
"Coraza de Teostra",
"Córtex de Teostra",
"Crin de Teostra",
"Crin de Teostra",
"Cola de Teostra",
"Látigo de Teostra",
"Cuerno de Teostra+",
"Asta de Teostra",
"Escama de dragón de fuego+",
"Esquirla de llamas",
"Garra de Teostra+",
"Garra dura de dragón de fuego",
"Membrana de Teostra",
"Aladura de Teostra",
"Polvo de Teostra",
"Gema de Teostra",
"Coraza de Lunastra",
"Córtex de Lunastra",
"Crin de Lunastra",
"Crin de Lunastra+",
"Cola de Lunastra",
"Látigo de Lunastra",
"Cuerno de Lunastra",
"Asta de Lunastra",
"Escama de Lunastra+",
"Esquirla de Lunastra",
"Ala de Lunastra",
"Aladura de Lunastra",
"Gema de Lunastra",
"Coraza de Daora",
"Córtex de Daora",
"Escama dragoniana de Daora+",
"Esquirla de Daora",
"Membrana de Daora",
"Aladura de Daora",
"Cuerno de Daora+",
"Asta de Daora",
"Cola de Daora",
"Látigo de Daora",
"Garra afilada de Daora",
"Garra dura de Daora",
"Gema de Daora",
"Escama fallecida",
"Esquirla de difunto",
"Coraza de Vaal Hazak",
"Córtex de Vaal Hazak",
"Membrana de Vaal Hazak",
"Membrana tejedora de muerte",
"Cola de Vaal Hazak",
"Mayal de Vaal Hazak",
"Colmillo de Vaal Hazak+",
"Colmillo perforasombra",
"Garra de Vaal Hazak",
"Garra dura de Vaal Hazak",
"Ala de Vaal Hazak",
"Aladura de Vaal Hazak",
"Gema de Vaal Hazak",
"Piel fina de Namielle",
"Aladura de Namielle",
"Bigote de Namielle",
"Látigo de Namielle",
"Garra dura de Namielle",
"Escama de alma de Xeno'jiiva",
"Caparazón de Xeno'jiiva",
"Velo de Xeno'jiiva",
"Cola de Xeno'jiiva",
"Cuerno de Xeno'jiiva",
"Garra de Xeno'jiiva",
"Ala de Xeno'jiiva",
"Gema de Xeno'jiiva",
"Esquirla de Safi'jiiva",
"Córtex de Safi'jiiva",
"Dracocaparazón pulsante",
"Látigo de Safi'jiiva",
"Asta de Safi'jiiva",
"Garra dura de Safi'jiiva",
"Aladura de Safi'jiiva",
"Cristal de Zionio",
"Escama dorada de Kulve Taroth",
"Escama dorada de Kulve Taroth+",
"Caparazón dorado Kulve Taroth",
"Caparazón dorado Kulve Taroth+",
"Garra dorada de Kulve Taroth",
"Garra dorada de Kulve Taroth+",
"Espiracorno dorado Kulve Taroth",
"Espiracorno dorado Kulve Taroth+",
"Caparazón de cola Kulve Taroth",
"Caparazón de cola Kulve Taroth+",
"Gema vela dorada Kulve Taroth",
"Dracoespira dorada",
"Asombrosa pepita Kulve Taroth",
"Escama blanda Shara Ishvalda",
"Armadura roca Shara Ishvalda",
"Armadura blanda Shara Ishvalda",
"Petalfósil de Shara Ishvalda",
"Garra blanda de Shara Ishvalda",
"Gema de Shara Ishvalda",
"Palio de Alatreon",
"Manto de Alatreon",
"Garfio de Alatreon",
"Ala salvaje de Alatreon",
"Cola salvaje de Alatreon",
"Timón de viento",
"Dracoespira celeste",
"Crin de Bégimo",
"Hueso de Bégimo",
"Gran cuerno de Bégimo",
"Garra guadaña de Bégimo",
"Cola de Bégimo",
"Fragmento de eterita",
"Garra de leshen",
"Garra de leshen antiguo",
"Cráneo de leshen",
"Cráneo de leshen antiguo",
"Hueso maldito",
"Hueso maldito de antiguo",
"Cuernos de leshen",
"Cuernos de leshen antiguo",
"Resina de leshen",
"Mutágeno",
"Trozo de draconita",
"Draconita",
"Draconita reluciente",
"Draconita guerrero (espada)",
"Draconita guerrero (filo)",
"Draconita guerrero (martillo)",
"Draconita guerrero (lanza)",
"Draconita guerrero (hacha)",
"Draconita guerrero (asta)",
"Draconita guerrero (proyectil)",
"Draconita héroe (espada)",
"Draconita héroe (filo)",
"Draconita héroe (martillo)",
"Draconita héroe (lanza)",
"Draconita héroe (hacha)",
"Draconita héroe (asta)",
"Draconita héroe (proyectil)",
"Cristal degradado",
"Cristal boscoso",
"Cristal próspero",
"Cristal Destino boscoso",
"Cristal agrietado",
"Cristal desértico",
"Cristal sereno",
"Cristal Destino desértico",
"Cristal pálido",
"Cristal arrecife coral",
"Cristal abisal",
"Cristal Destino coralino",
"Cristal distorsionado",
"Cristal pútrido",
"Cristal de puesta de sol",
"Cristal Destino pútrido",
"Cristal fundido",
"Cristal volcánico",
"Cristal ardiente",
"Cristal Destino volcánico",
"Cristal helado",
"Cristal ártico",
"Cristal del amanecer",
"Cristal Destino ártico",
"Gran hueso musgoso",
"Gran hueso forestal",
"Gran hueso dormido",
"Dracohueso Destino forestal",
"Litohueso erosionado",
"Litohueso del páramo",
"Litohueso curtido",
"Dracohueso Destino desértico",
"Hueso carmesí vívido",
"Hueso carmesí de coral",
"Hueso carmesí vibrante",
"Dracohueso Destino coralino",
"Deliriohueso deformado",
"Deliriohueso de efluvio",
"Deliriohueso afectado",
"Dracohueso Destino pútrido",
"Hueso salvaje efervescente",
"Hueso salvaje volcánico",
"Hueso salvaje dracocombusto",
"Dracohueso Destino volcánico",
"Hueso de hielo viejo",
"Hueso helado ártico",
"Hueso de hielo permahelado",
"Dracohueso Destino ártico",
"Hueso de dracovena feroz",
"Hueso de dracovena pesado",
"Hueso sólido de dracovena",
"Hueso de dracovena anciano",
"Trafagohueso vena espiritual",
"Hueso sólido vena espiritual",
"Hueso vena espiritual anciano",
"Esquirla de gema vena espiritual",
"Gema de vena espiritual",
"Gran gema de vena espiritual",
"Crin áspera",
"Pluma colorida",
"Vesícula de veneno aromática",
"Vesícula de veneno curtida",
"Vesícula hídrica",
"Vesícula torrencial curtida",
"Corona de barro",
"Corona curtida",
"Cátodo cegador",
"Cátodo curtido",
"Púa vípera tentadora",
"Púa vípera curtida",
"Gran cuerno ancestral",
"Gran cuerno curtido",
"Piel flamígera brillante",
"Piel flamígera curtida",
"Piel atronadora chisporroteante",
"Piel atronadora curtida",
"Escama de reina",
"Escama verde curtida",
"Escama rosada",
"Escama rosada curtida",
"Fotóforo cegador",
"Caparazón de goma",
"Caparazón de goma curtido",
"Piel de obsidiana",
"Piel curtida",
"Capucha de medianoche",
"Aceite tintado+",
"Aceite curtido+",
"Mandíbula pesada",
"Aleta de magma incandescente",
"Aleta de magma curtida",
"Peto metálico",
"Peto curtido",
"Colmillo helado de sangre fría",
"Colmillo helado curtido",
"Piel plateada siniestra",
"Piel de lobo plateado curtida",
"Pellejo de hielo suave",
"Pellejo de hielo curtido",
"Pellejo congelado de cristal",
"Pellejo congelado curtido",
"Garra guadaña mortífera",
"Garra guadaña curtida",
"Garra segadora de almas",
"Garra curtida",
"Escama de rey",
"Escama roja curtida",
"Escama celeste",
"Escama celeste curtida",
"Corajecorno enroscado",
"Espiracorno enroscado",
"Tiranocorno nudo negro",
"Espiracorno nudo negro",
"Cuchilla de asesino",
"Cuchilla curtida",
"Punta de cola flameante",
"Punta de cola curtida",
"Cola pulida",
"Cola curtida",
"Caparazón de ébano brillante",
"Caparazón de ébano curtido",
"Mandíbula de campeón",
"Mandíbula curtida",
"Mandíbula negra trémula",
"Mandíbula de ébano curtida",
"Electrificador letal cargado",
"Electrificador curtido",
"Escama explosiva púrpura",
"Escama explosiva curtida",
"Piel ébano sanguinolenta",
"Piel manchada",
"Cuerno celeste solemne",
"Cuerno celeste curtido",
"Crin de fuego infernal",
"Crin bermellón curtida",
"Ala acerada del clamatormentas",
"Ala férrea curtida",
"Crin celeste",
"Crin celeste curtida",
"Cornacorona de aurora",
"Cornacorona curtida",
"Colmillo crepuscular",
"Colmillo crepuscular curtido",
"Piel fina encantadora",
"Piel de trance curtida",
"Gran cuerno de extinción",
"Cuerno aniquilador curtido",
"Escama luz de luna",
"Escama dorada curtida",
"Escama abrasadora",
"Escama plateada curtida",
"Dracáscara brotante",
"Dracáscara curtida",
"Piel brillante sangrienta",
"Piel brillante curtida",
"Cupón",
"Cupón gourmet",
"Sello de primer wyveriano",
"Sello primer wyveriano de lujo",
"Sello sublime primer wyveriano",
"Sello wyveriano de acero",
"Sello wyveriano de plata",
"Sello wyveriano de oro",
"Sello wyveriano celestial",
"Vale de fusión acerada",
"Vale de fusión argéntea",
"Vale de fusión áurea",
"Vale de fusión astral",
"Recomendación",
"Gran recomendación",
"Sello conquistador",
"Billete de la comisión",
"Billete de la comisión+",
"Cupón de buscatrufos",
"Dibujo Gajalaka",
"Vale de Boaboa",
"Vale de flores de primavera",
"Vale puesta de sol de verano",
"Vale de cosecha de otoño",
"Vale estrella de invierno",
"Vale de gratitud",
"Insectario de primavera",
"Insectario de verano",
"Vale de Vaal Hazak",
"Vale de Kirin",
"Vale de Teostra",
"Vale de Lunastra",
"Vale de Kushala Daora",
"Vale de Nergigante",
"Vale de Zorah Magdaros",
"Vale de Xeno'jiiva",
"Vale de Namielle",
"Vale Cynodon",
"Vendaje negro",
"Vale cristal negro",
"Vale de la 1.ª flota",
"Vale de escarabajo",
"Vale de Mega Man",
"Fragmento de estrella celeste",
"Gema estrella celeste",
"Orbe rojo",
"Planos del maestro artesano",
"Vale Bushi",
"Prisma encantador",
"Pluma de Senu",
"Vale de carrao algodón",
"Vale de carrao rasposo",
"Vale de Kulu-Ya-Ku",
"Vale de gorgasia",
"Tícket falso",
"Tícket falso II",
"Tícket falso III",
"Vale termal",
"Vale de vapor",
"Vale lunar",
"Vale lunar VIP",
"Vale astral",
"Vale astral VIP",
"Vale floral",
"Vale congelador",
"Vale termargénteo",
"Plano de Águila Negra",
"Cazuela de gorgasia",
"Insignia S.T.A.R.S.",
"Vale de pingüino",
"Tejido sellado dragón",
"Vale fortachón",
"Vale pico de minería",
"Vale wyveriano",
"Vale festivo",
"Símbolo de unidad",
"Vale carnívoro de la cantina",
"Vale de caballa cuchillo",
"Vale de carrao algodón II",
"Moneda Pukei",
"Moneda Kulu",
"Moneda Rathian",
"Moneda Tzitzi",
"Moneda Barroth",
"Moneda Gama",
"Moneda Rathalos",
"Moneda brutal",
"Moneda voladora",
"Moneda pináculo",
"Moneda del rey cazador",
"Moneda del cazador estrella",
"Moneda Banbaro",
"Moneda Paolumu",
"Moneda Narga",
"Moneda Glavenus",
"Moneda Odogaron",
"Moneda Zinogre",
"Moneda cinturón negro",
"Moneda del rey héroe",
"Moneda Tigrex",
"Pedazo de dracofuerza",





"Huevo de acero",
"Huevo de plata",
"Huevo de oro",
"Escama astillada",
"Escama grande",
"Escama bonita",
"Escama lustrosa",
"Escama reluciente",
"Escama gigante",
"Escama magnífica",
"Piedra Bherna",
"Dundomarino",
"Mineral Loc Lac",
"Cuarzo Val Habar",
"Minagardenita",
"Escama dorada",
"Escama dorada+",
"Escama de platino",
"Escama de platino+",
"Escama de oropel",
"Escama de oropel+",
"Concha esmeralda",
"Esquirla de oro",
"Pepita de oro",
"Fragmento de oro",
"Pieza de oro",
"Piel espléndida",
"D normal nv1",
"D normal nv2",
"D normal nv3",
"D perforante nv1",
"D perforante nv2",
"D perforante nv3",
"D abanico nv1",
"D abanico nv2",
"D abanico nv3",
"D explosivo nv1",
"D explosivo nv2",
"D explosivo nv3",
"D racimo nv1",
"D racimo nv2",
"D racimo nv3",
"D fuego",
"D agua",
"D rayo",
"D hielo",
"D draco",
"D veneno nv1",
"D veneno nv2",
"D paralizante nv1",
"D paralizante nv2",
"D sueño nv1",
"D sueño nv2",
"D fatiga nv1",
"D fatiga nv2",
"D recuperación nv1",
"D recuperación nv2",
"D wyvern",
"D cortante",
"D tranquilizante",
"D demonio",
"D armadura",
"Vial quemarropa",
"Vial de potencia",
"Vial de veneno",
"Vial paralizante",
"Vial de sueño",
"Vial de nitro",
"Joya misteriosa",
"Joya brillante",
"Joya gastada",
"Joya deforme",
"Joya ancestral",
"Joya tallada",
"Joya sellada",
"Joya fusión acerada",
"Joya fusión argéntea",
"Joya fusión áurea",
"Joya fusión astral",
"Draconita sucia",
"Draconita brillante",
"Arma disuelta",
"Arma fusionada",
"Arma sublimada",
"Arma incandescente",
"Hígado blanco",
"Lágrima de wyvern",
"Lágrima de wyvern G",
"Tesoro de dragón",
"Tesoro de dragón antiguo",
"Piedra transparente",
"Flor de sol",
"Flor de luz",
"Flor de oro",
"Sombrero de seta gourmet",
"Seta exquisita",
"Seta espiritual",
"Cactus bola",
"Cactus joya",
"Cactus regio",
"Durípero",
"Roquípero",
"Silvípero",
"Superabulón",
"Abulón selecto",
"Abulón precioso",
"Perla de luz",
"Perla profunda",
"Perla inocente",
"Fósil olvidado",
"Fósil legendario",
"Fósil místico",
"Fruto subterráneo",
"Fruto impuro",
"Fruto elíseo",
"Ámbar de Gaia",
"Ámbar dracovena",
"Ámbar antiguo",
"Berilio azul",
"Berilio real",
"Berilio abisal",
"Seta lunar",
"Dracoflor",
"Piña celestial",
"Abulón violeta",
"Perla de platino",
"Fósil perverso",
"Cielobaya",
"Piedra crepuscular",
"Piedra de Noé",
"Escama podrida",
"Escama luminosa",
"Petasites joven",
"Petasites exquisita",
"Petasites milenaria",
"Flor de hielo",
"Flor de hielo luz de luna",
"Flor de hielo pico nevado",
"Blancanieves",
"Pétalo de cristal",
"Esquirla de hueso cristalizado",
"Hueso de monstruo cristalizado",
"Hueso de dragón anciano cristalizado",
"Lágrima de bestia grande",
"Medicamento",
"Medicamento+",
"Ración (apoyo)",
"Polvo de vida (apoyo)",
"Fuente de vida (apoyo)",
"Poción máxima (apoyo)",
"Bomba barril grande (apoyo)",
"Trampa eléctrica (apoyo)",
"Trampa de escollo (apoyo)",
"Polvo de hierbas (apoyo)",
"Polvo de demonio (apoyo)",
"Polvo de cáscara (apoyo)",
"Cápsula flash (apoyo)",
"Cápsula chillona (apoyo)",
"Cápsula boñiga (apoyo)",
"Navaja aérea",
"Navaja tóxica",
"Cuchillo sedante",
"Navaja paralizante",
"Cuchillo tranquilizante",
"Bola transportadora (apoyo)",
"Bola tranquilizante (apoyo)",
"Hierba verde",
"Hierba roja",
"Hierba mixta (V+R)"]
