nombresMonstruo = {
    "Gran Jagras": "Gran Jagras",
    "Great Jagras": "Gran Jagras",
    "Kulu Ya Ku": "Kulu-Ya-Ku",
    "Pukei Pukei": "Pukei-Pukei",
    "Loro": "Pukei-Pukei",
    "Camaleon": "Pukei-Pukei",
    "Camaleón": "Pukei-Pukei",
    "Barroth": "Barroth",
    "Jyuratodus": "Jyuratodus",
    "Tobi Kadachi": "Tobi-Kadachi",
    "Anjanath": "Anjanath",
    "Rathian": "Rathian",
    "Tzitzi Ya Ku": "Tzitzi-Ya-Ku",
    "Pikachu": "Tzitzi-Ya-Ku",
    "Paolumu": "Paolumu",
    "Paulomu": "Paolumu",
    "Palomu": "Paolumu",
    "Gran Girros": "Gran Girros",
    "Great Girros": "Gran Girros",
    "Radobaan": "Radobaan",
    "Legiana": "Legiana",
    "Odogaron": "Odogaron",
    "Rathalos": "Rathalos",
    "Diablos": "Diablos",
    "Kirin": "Kirin",
    "Zorah Magdaros": "Zorah Magdaros",
    "Dodogama": "Dodogama",
    "Bazelgeuse": "Bazelgeuse",
    "Deviljho": "Deviljho",
    "Pepinillo": "Deviljho",
    "Pickle": "Deviljho",
    "Lavasioth": "Lavasioth",
    "Uragaan": "Uragaan",
    "Nergigante": "Nergigante",
    "Teostra": "Teostra",
    "Lunastra": "Lunastra",
    "Kushala Daora": "Kushala Daora",
    "Vaal Hazak": "Vaal Hazak",
    "Kulve Taroth": "Kulve Taroth",
    "Xeno jiiva": "Xeno'jiiva",
    "Xeno'jiiva": "Xeno'jiiva",
    "Beotodus": "Beotodus",
    "Banbaro": "Banbaro",
    "Barioth": "Barioth",
    "Nargacuga": "Nargacuga",
    "Naruga Kuruga": "Nargacuga",
    "Glavenus": "Glavenus",
    "Tigrex": "Tigrex",
    "Brachydios": "Brachydios",
    "Velkhana": "Velkhana",
    "Namielle": "Namielle",
    "Shara Ishvalda": "Shara Ishvalda",
    "Zinogre": "Zinogre",
    "Jinouga": "Zinogre",
    "Yian Garuga": "Yian Garuga",
    "Safi jiiva": "Safi jiiva",
    "Rajang": "Rajang",
    "Alatreon": "Alatreon",
    "Begimo": "Bégimo",
    "Bégimo": "Bégimo",
    "Behemoth": "Bégimo",
    "Leshen": "Leshen",
    "Rathian Rosa": "Rathian Rosa",
    "Pink Rathian": "Rathian Rosa",
    "Rathalos Celeste": "Rathalos Celeste",
    "Azure Rathalos": "Rathalos Celeste",
    "Rathian Dorada": "Rathian Dorada",
    "Gold Rathian": "Rathian Dorada",
    "Rathalos Plateado": "Rathalos Plateado",
    "Silver Rathalos": "Rathalos Plateado",
    "Diablos Negra": "Diablos Negra",
    "Black Diablos": "Diablos Negra",
    "Tobi Kadachi Vipero": "Tobi-Kadachi Vípero",
    "Tobi Kadachi Vípero": "Tobi-Kadachi Vípero",
    "Viper Tobi Kadachi": "Tobi-Kadachi Vípero",
    "Paolumu Somnus": "Paolumu Somnus",
    "Nightshade Paolumu": "Paolumu Somnus",
    "Pukei Pukei Coralino": "Pukei-Pukei Coralino",
    "Coral Pukei Pukei": "Pukei-Pukei Coralino",
    "Legiana Aullador": "Legiana Aullador",
    "Shrieking Legiana": "Legiana Aullador",
    "Anjanath Fulgúreo": "Anjanath Fulgúreo",
    "Anjanath Fulgureo": "Anjanath Fulgúreo",
    "Fulgur Anjanath": "Anjanath Fulgúreo",
    "Glavenus Acídico": "Glavenus Acídico",
    "Glavenus Acidico": "Glavenus Acídico",
    "Acidic Glavenus": "Glavenus Acídico",
    "Odogaron Ébano": "Odogaron Ébano",
    "Ebony Odogaron": "Odogaron Ebano",
    "Bazelgeuse Magma": "Bazelgeuse Magma",
    "Seething Bazelgeuse": "Bazelgeuse Magma",
    "Vaal Hazak Espóreo": "Vaal Hazak Espóreo",
    "Vaal Hazak Esporeo": "Vaal Hazak Espóreo",
    "Blackveil Vaal Hazak": "Vaal Hazak Espóreo",
    "Deviljho Salvaje": "Deviljho Salvaje",
    "Pepinillo Salvaje": "Deviljho Salvaje",
    "Savage Deviljho": "Deviljho Salvaje",
    "Savage Pickle": "Deviljho Salvaje",
    "Nergigante Regio": "Nergigante Regio",
    "Ruiner Nergigante": "Nergigante Regio",
    "Yian Garuga Naevus": "Yian Garuga Naevus",
    "Scarred Yian Garuga": "Yian Garuga Naevus",
    "Tigrex Pardo": "Tigrex Pardo",
    "Brute Tigrex": "Tigrex Pardo",
    "Zinogre Estigio": "Zinogre Estigio",
    "Jinouga Estigio": "Zinogre Estigio",
    "Stygian Zinogre": "Zinogre Estigio",
    "Stygian Jinouga": "Zinogre Estigio",
    "Rajang Rabioso": "Rajang Rabioso",
    "Furious Rajang": "Rajang Rabioso",
    "Brachydios Colérico": "Brachydios Colérico",
    "Brachydios Colerico": "Brachydios Colérico",
    "Raging Brachydios": "Brachydios Colérico",
    "Barioth Cynodon": "Barioth Cynodon",
    "Frostfang Barioth": "Barioth Cynodon",
    "Leshen Antiguo": "Leshen Antiguo",
    "Ancient Leshen": "Leshen Antiguo"
}
