nombresMonstruo = {
    "Gran Jagras": "Great Jagras",
    "Great Jagras": "Great Jagras",
    "Kulu Ya Ku": "Kulu-Ya-Ku",
    "Pukei Pukei": "Pukei-Pukei",
    "Loro": "Pukei-Pukei",
    "Camaleon": "Pukei-Pukei",
    "Camaleón": "Pukei-Pukei",
    "Barroth": "Barroth",
    "Jyuratodus": "Jyuratodus",
    "Tobi Kadachi": "Tobi-Kadachi",
    "Anjanath": "Anjanath",
    "Rathian": "Rathian",
    "Tzitzi Ya Ku": "Tzitzi-Ya-Ku",
    "Pikachu": "Tzitzi-Ya-Ku",
    "Paolumu": "Paolumu",
    "Paulomu": "Paolumu",
    "Palomu": "Paolumu",
    "Gran Girros": "Great Girros",
    "Great Girros": "Great Girros",
    "Radobaan": "Radobaan",
    "Legiana": "Legiana",
    "Odogaron": "Odogaron",
    "Rathalos": "Rathalos",
    "Diablos": "Diablos",
    "Kirin": "Kirin",
    "Zorah Magdaros": "Zorah Magdaros",
    "Dodogama": "Dodogama",
    "Bazelgeuse": "Bazelgeuse",
    "Deviljho": "Deviljho",
    "Pepinillo": "Deviljho",
    "Pickle": "Deviljho",
    "Lavasioth": "Lavasioth",
    "Uragaan": "Uragaan",
    "Nergigante": "Nergigante",
    "Teostra": "Teostra",
    "Lunastra": "Lunastra",
    "Kushala Daora": "Kushala Daora",
    "Vaal Hazak": "Vaal Hazak",
    "Kulve Taroth": "Kulve Taroth",
    "Xeno jiiva": "Xeno'jiiva",
    "Xeno'jiiva": "Xeno'jiiva",
    "Beotodus": "Beotodus",
    "Banbaro": "Banbaro",
    "Barioth": "Barioth",
    "Nargacuga": "Nargacuga",
    "Naruga Kuruga": "Nargacuga",
    "Glavenus": "Glavenus",
    "Tigrex": "Tigrex",
    "Brachydios": "Brachydios",
    "Velkhana": "Velkhana",
    "Namielle": "Namielle",
    "Shara Ishvalda": "Shara Ishvalda",
    "Zinogre": "Zinogre",
    "Jinouga": "Zinogre",
    "Yian Garuga": "Yian Garuga",
    "Safi jiiva": "Safi jiiva",
    "Rajang": "Rajang",
    "Alatreon": "Alatreon",
    "Begimo": "Begimo",
    "Bégimo": "Begimo",
    "Behemoth": "Bégimo",
    "Leshen": "Leshen",
    "Rathian Rosa": "Pink Rathian",
    "Pink Rathian": "Pink Rathian",
    "Rathalos Celeste": "Azure Rathalos",
    "Azure Rathalos": "Azure Rathalos",
    "Rathian Dorada": "Gold Rathian",
    "Gold Rathian": "Gold Rathian",
    "Rathalos Plateado": "Silver Rathalos",
    "Silver Rathalos": "Silver Rathalos",
    "Diablos Negra": "Black Diablos",
    "Black Diablos": "Black Diablos",
    "Tobi Kadachi Vipero": "Viper Tobi Kadachi",
    "Tobi Kadachi Vípero": "Viper Tobi Kadachi",
    "Viper Tobi Kadachi": "Viper Tobi Kadachi",
    "Paolumu Somnus": "Nightshade Paolumu",
    "Nightshade Paolumu": "Nightshade Paolumu",
    "Pukei Pukei Coralino": "Coral Pukei Pukei",
    "Coral Pukei Pukei": "Coral Pukei Pukei",
    "Legiana Aullador": "Shrieking Legiana",
    "Shrieking Legiana": "Shrieking Legiana",
    "Anjanath Fulgúreo": "Fulgur Anjanath",
    "Anjanath Fulgureo": "Fulgur Anjanath",
    "Fulgur Anjanath": "Fulgur Anjanath",
    "Glavenus Acídico": "Acidic Glavenus",
    "Glavenus Acidico": "Acidic Glavenus",
    "Acidic Glavenus": "Acidic Glavenus",
    "Odogaron Ébano": "Ebony Odogaron",
    "Ebony Odogaron": "Ebony Odogaron",
    "Bazelgeuse Magma": "Seething Bazelgeuse",
    "Seething Bazelgeuse": "Seething Bazelgeuse",
    "Vaal Hazak Espóreo": "Blackveil Vaal Hazak",
    "Vaal Hazak Esporeo": "Blackveil Vaal Hazak",
    "Blackveil Vaal Hazak": "Blackveil Vaal Hazak",
    "Deviljho Salvaje": "Savage Deviljho",
    "Pepinillo Salvaje": "Savage Deviljho",
    "Savage Deviljho": "Savage Deviljho",
    "Savage Pickle": "Savage Deviljho",
    "Nergigante Regio": "Ruiner Nergigante",
    "Ruiner Nergigante": "Ruiner Nergigante",
    "Yian Garuga Naevus": "Scarred Yian Garuga",
    "Scarred Yian Garuga": "Scarred Yian Garuga",
    "Tigrex Pardo": "Brute Tigrex",
    "Brute Tigrex": "Brute Tigrex",
    "Zinogre Estigio": "Stygian Zinogre",
    "Jinouga Estigio": "Stygian Zinogre",
    "Stygian Zinogre": "Stygian Zinogre",
    "Stygian Jinouga": "Stygian Zinogre",
    "Rajang Rabioso": "Furious Rajang",
    "Furious Rajang": "Furious Rajang",
    "Brachydios Colérico": "Raging Brachydios",
    "Brachydios Colerico": "Raging Brachydios",
    "Raging Brachydios": "Raging Brachydios",
    "Barioth Cynodon": "Frostfang Barioth",
    "Frostfang Barioth": "Frostfang Barioth",
    "Leshen Antiguo": "Ancient Leshen",
    "Ancient Leshen": "Ancient Leshen",
    "Fatalis": "Fatalis"
}
